const questions = [
  {
    age: 0,
    question: [
      "Can your child lift it's head when on his tummy?",
      "Does your child respond to sound?",
      "Does your child stare at faces? ",
      "Does your child turn it's head towards light?",
    ],
  },
  {
    age: 1,
    question: [
      "Can your child lift it's head when on his tummy?",
      "Does your child respond to sound?",
      "Does your child stare at faces? ",
      "Does your child turn it's head towards light?",
    ],
  },
  {
    age: 2,
    question: [
      "Can your child lift it's head when on his tummy?",
      "Does your child respond to loud sounds?",
      "Does your child stare at faces? ",
      "Does your child turn it's head towards light?",
      "Does your child smile at people?",
      "Does your child watch things as they move?",
      "Does your child bring hands to mouth?",
    ],
  },
  {
    age: 3,
    question: [
      "Does your child smile at people?",
      "Does your child bring hands to mouth?",
      "Does your child try to look at parents?",
      "Does your child make cooing and gurgling sounds?",
      "Does your child turn its head towards sounds?",
      "Does your child pay attention to faces?",
      "Is your child beginning to follow things with eyes?",
      "Is your child beginning to act bored(crying/fussy) if activity doesn't change?",
      "Can your child hold head up and begin to push up when lying on tummy?",
    ],
  },
  {
    age: 4,
    question: [
      "Does your child make cooing and gurgling sounds?",
      "Does your child respond to loud sounds?",
      "Does your child watch things as they move?",
      "Does your child smile at people?",
      "Does your child bring hands to mouth?",
      "Can your child hold head steady?",
      "Can your child recognize your face?",
      "Does your child push down with legs when feet are placed on a hard surface?",
    ],
  },
  {
    age: 5,
    question: [
      "Does your child smile at people?",
      "Does your child like to play with people and sometimes cries when playing stops?",
      "Does your child copy some expressions like smiling and frowning?",
      "Does your child make cooing and gurgling sounds?",
      "Does your child cry in different ways to show hunger, pain or tiredness?",
      "Is your child able to make you understand if it is happy or sad?",
      "Can your child hold head up steadily?",
      "Does your child respond to affection?",
      "Does your child reach for toy with one hand?",
      "Does your child use hands and eyes together, such as seeing a toy and reaching for it?",
      "Does your child follow moving things with eyes from side to side without difficulty?",
      "Does your child watch faces closely?",
      "Does your child recognize familiar people and things at a distance?",
      "Does your child hold head up without support?",
      "Does your child push down with legs when feet are placed on a hard surface?",
      "Does your child bring hands to mouth?",
      "Does your child hold a toy and shake it and swing at dangling toys?",
    ],
  },
  {
    age: 6,
    question: [
      "Does your child try to get hold of things within reach?",
      "Does your child respond to affection?",
      "Does your child turn towards sounds and voices?",
      "Does your child bring hands to mouth?",
      'Does your child make vowel sounds ("ah", "oh", "eh")?',
      "Can your child roll over from tummy to back?",
      "Does your child roll over in both directions?",
      "Does your child laugh or make squealing sounds?",
      "Does your child amuse itself by playing with hands and feet?",
    ],
  },
  {
    age: 7,
    question: [
      "Does your child know familiar faces and begins to know if someone is a stranger?",
      "Does your child like to play with others, especially parents?",
      "Does your child respond to other's emotions and often seems happy?",
      "Does your child likes to look at self in a mirror?",
      "Does your child respond to sounds by making sounds?",
      "Does your child string vowels together when babbling (“ah,” “eh,” “oh”) and likes taking turns with parent while making sounds ?",
      "Is your child beginning to respond to own name?",
      "Does your child make sounds to show happiness or sadness?",
      'Is your child beginning to say consonant sounds like "m", "b"?',
      "Does your child look around at things nearby?",
      "Does your child bring things to mouth?",
      "Is your child beginning to show curiosity about things and try to get things which are out of reach?",
      "Is your child beginning to pass things from one hand to the other ?",
      "Does your child roll over in both directions?",
      "Is yor child beginning to sit without support?",
      "When standing, does your child support weight on legs or bounce?",
      "Is your child ready for solid foods?",
    ],
  },
  {
    age: 8,
    question: [
      "Does your child know familiar faces and begins to know if someone is a stranger?",
      "Does your child like to play with others, especially parents?",
      "Does your child respond to other's emotions and often seems happy?",
      "Does your child likes to look at self in a mirror?",
      "Can your child reach for things with a sweeping motion?",
      "Does your child imitate speech sounds (babbles)?",
      "Does your child look around at things nearby?",
      "Does your child bring things to mouth?",
      "Is your child beginning to show curiosity about things and try to get things which are out of reach?",
      "Is your child beginning to pass things from one hand to the other ?",
      "Does your child roll over in both directions?",
      "Is yor child beginning to sit without support?",
      "When standing, does your child support weight on legs or bounce?",
      "Is your child ready for solid foods?",
    ],
  },
  {
    age: 9,
    question: [
      "When standing, does your child support weight on legs or bounce?",
      "Can your child sit with support?",
      'Can your child say "papa"/"mama"/"dada" to both parents (isn\'t specific to parent)?',
      "Does your child play games involving back-and-forth play?",
      "Can your child pass objects from hand to hand?",
      "Does your child respond to own name?",
      "Does your child know familiar faces and begins to know if someone is a stranger?",
      "Does your child look where you point?",
    ],
  },
  {
    age: 10,
    question: [
      "Is your child sometimes afraid of strangers?",
      "Is your child sometimes clingy with familiar adults?",
      "Does your child have favourite toys?",
      'Does your child understand "no"?',
      "Does your child make a lot of different sounds like “mamamama” and “bababababa”?",
      "Does your child copy sounds and gestures of others?",
      "Does your child use fingers to point at things?",
      "Does your child watch the path of something as it falls?",
      "Does your child look for things that it sees you hide?",
      "Does your child play peek-a-boo?",
      "Does your child put things in mouth?",
      "Does your child move things smoothly from hand to another?",
      "Does your child pick up things like cereal between thumb and index finger?",
      "Does your child stand while holding on?",
      "Can your child get into sitting positions?",
      "Does your child crawl?",
      "When standing, does your child support weight on legs or bounce?",
      "Can your child combine syllables into word-like sounds?",
      "Does your child bang, drop, and throw objects?",
      "Does your child try to grasp spoon when being fed?",
    ],
  },
  {
    age: 11,
    question: [
      "Is your child sometimes afraid of strangers?",
      "Is your child sometimes clingy with familiar adults?",
      "Does your child have favourite toys?",
      'Does your child understand "no"?',
      "Does your child make a lot of different sounds like “mamamama” and “bababababa”?",
      "Does your child copy sounds and gestures of others?",
      "Does your child use fingers to point at things?",
      "Does your child watch the path of something as it falls?",
      "Does your child look for things that it sees you hide?",
      "Does your child play peek-a-boo?",
      "Does your child put things in mouth?",
      "Does your child move things smoothly from hand to another?",
      "Does your child stand while holding on?",
      "Can your child get into sitting positions?",
      "When standing, does your child support weight on legs or bounce?",
      "Can your child combine syllables into word-like sounds?",
      "Does your child bang, drop, and throw objects?",
      "Does your child try to grasp spoon when being fed?",
      "Can your child pick things up with claw grasp?",
      "Does your child crawl well?",
    ],
  },
  {
    age: 12,
    question: [
      "Does your child crawl well?",
      "Can your child stand while supported?",
      "Does your child look for things that it sees you hide?",
      "Can your child say “papa” and “mama” to the right parent (is specific to parent)?",
      "Does your child learn gestures like shaking head or waving?",
      "Does your child point at objects?",
      "Does your child retain the skills it had before?",
      "Is your child sometimes shy or nervous with strangers?",
      "Does your child cry when mom or dad leaves?",
      "Does your child bang, drop, and throw objects?",
    ],
  },
  {
    age: 13,
    question: [
      "Is your child sometimes shy or nervous with strangers?",
      "Does your child cry when mom or dad leaves?",
      "Does your child have favourite things and people?",
      "Does your child show fear in some situations?",
      "Does your child hand you a book when he wants to hear a story?",
      "Does your child repeat sounds or actions to get attention?",
      "Does your child put out arm or leg to help with dressing?",
      "Does your child play games like peek-a-boo and pat-a-cake?",
      "Does your child respond to simple spoken requests?",
      "Does your child use simple gestures like shaking head(no) or waving(bye-bye)?",
      "Can your child say “papa” and “mama” to the right parent (is specific to parent)?",
      "Does your child try to say words you say?",
      "Does your child bang, drop, and throw objects?",
      "Does your child look at right picture or thing when it is named?",
      "Does your child copy gestures?",
      "Does your child use things correctly like drinking from cup or brushing hair with comb?",
      "Does your child put things in a container, take things out of a container?",
      "Does your child let things go without help?",
      "Does your child poke with index finger?",
      "Does your child stand and sit?",
    ],
  },
  {
    age: 14,
    question: [
      "Is your child sometimes shy or nervous with strangers?",
      "Does your child cry when mom or dad leaves?",
      "Does your child have favourite things and people?",
      "Does your child show fear in some situations?",
      "Does your child hand you a book when he wants to hear a story?",
      "Does your child repeat sounds or actions to get attention?",
      "Does your child put out arm or leg to help with dressing?",
      "Does your child play games like peek-a-boo and pat-a-cake?",
      "Does your child respond to simple spoken requests?",
      "Does your child use simple gestures like shaking head(no) or waving(bye-bye)?",
      "Can your child say “papa” and “mama” to the right parent (is specific to parent)?",
      "Does your child try to say words you say?",
      'Does your child use one or two words skilfully? (e.g. "hello" and "bye")',
      "Can your child bend over and pick up an object?",
      "Can your child stand alone?",
      "Does your child use things correctly like drinking from cup or brushing hair with comb?",
      "Does your child put things in a container, take things out of a container?",
      "Does your child let things go without help?",
      "Does your child poke with index finger?",
    ],
  },
  {
    age: 15,
    question: [
      "Does your child finger feed?",
      "Does your child let things go without help?",
      "Does your child poke with index finger?",
      "Can your child empty containers of contents?",
      "Is your child able to imitate others?",
      "Can your child bend over and pick up an object?",
      "Can your child stand alone?",
    ],
  },
  {
    age: 16,
    question: [
      "Does your child finger feed?",
      "Can your child empty containers of contents?",
      "Is your child able to imitate others?",
      "Does your child play with a ball?",
      "Can your child say five words skilfully?",
      "Can your child walk backwards?",
    ],
  },
  {
    age: 17,
    question: [
      "Does your child finger feed?",
      "Can your child empty containers of contents?",
      "Is your child able to imitate others?",
      "Does your child play with a ball?",
      "Can your child say five words skilfully?",
      "Can your child walk backwards?",
      "Does your child turn the pages of a book?",
      "Does your child have temper tantrums when frustrated?",
      "Is your child attached to a soft toy or other object?",
    ],
  },
  {
    age: 18,
    question: [
      "Does your child point to show things to others?",
      "Does your child walk?",
      "Does your child copy others?",
      "Does your child gain new words?",
      "Does your child retain the skills it had before?",
      "Does your child turn the pages of a book?",
      "Does your child have temper tantrums when frustrated?",
      "Is your child attached to a soft toy or other object?",
      "Does your child use a handful of words regularly?",
      "Does your child enjoy pretend games?",
      "Does your child like riding toys?",
    ],
  },

  {
    age: 19,
    question: [
      "Does your child like to hand things to others as play ?",
      "Does your child have temper tantrums?",
      "Does your child copy others?",
      "Is your child sometimes shy or nervous with strangers?",
      "Does your child respond to and give affection?",
      "Does your child play simple pretend games such as feeding a doll?",
      "Does your child cling to caregivers in new situations?",
      "Does your child point to show others something interesting?",
      "Does your child say several single words?",
      "Does your child says and shakes head(no)?",
      "Does your child know what ordinary things are for - like telephone, brush, spoon?",
      "Does your child like riding toys?",
      "Does your child look at picture books on his own?",
      "Can your child pedal when put on tricycle with parent’s handle?",
      "Can your child scribble well?",
      'Does your child follow one step verbal commands without any gestures, for example, sits when you say "sit down"?',
      "Can your child walk alone?",
      "Can your child drink from a cup and eat with a spoon?",
    ],
  },
  {
    age: 20,
    question: [
      "Can your child use a spoon and fork?",
      "Can your child run?",
      "Can your child throw a ball underarm?",
      "Does your child say several single words?",
      "Does your child says and shakes head(no)?",
      "Does your child know what ordinary things are for - like telephone, brush, spoon?",
      "Does your child like riding toys?",
      "Does your child look at picture books on his own?",
      "Can your child pedal when put on tricycle with parent’s handle?",
      "Can your child scribble well?",
      'Does your child follow one step verbal commands without any gestures, for example, sits when you say "sit down"?',
    ],
  },
  {
    age: 21,
    question: [
      "Does your child pretend to feed a doll?",
      "Can your child take off own clothes with help?",
      "Does your child throw away an object such as rubbish, in imitation?",
      "Does your child know what ordinary things are for - like telephone, brush, spoon?",
    ],
  },
  {
    age: 22,
    question: [
      "Can your child walk up steps?",
      "Does your child enjoy helping around the house?",
      "Can your child set simple goals (e.g. deciding to put a toy in a certain place)?",
      "Does your child know what ordinary things are for - like telephone, brush, spoon?",
    ],
  },
  {
    age: 23,
    question: [
      "Can your child kick a ball forward?",
      "Does your child follow two-step requests? (Example: get your doll and bring it here)",
      "Does your child copy others' behaviour?",
      "Does your child know what ordinary things are for - like telephone, brush, spoon?",
    ],
  },
  {
    age: 24,
    question: [
      "Can your child make a tower of 4-5 blocks?",
      "Can your child name a simple picture in a book?",
      "Can your child use about 50 different words?",
      'Does your child use two word phrases like "drink milk"?',
      "Does your child copy others' actions and words?",
      "Does your child know what ordinary things are for - like telephone, brush, spoon, fork?",
      "Does your child follow simple instructions?",
      "Does your child walk steadily?",
      "Does your child retain the skills it had before?",
    ],
  },
  {
    age: 25,
    question: [
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child show defiant behaviour(doing what he has been told not to)?",
      "Is your child starting to include other children in games, like chase games?",
      "Does your child point to things or pictures which are named?",
      "Does your child say sentences with 2-4 words?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child play simple make-believe games?",
      "Does your child build towers of 4 or more blocks?",
      "Does your child follow two-step instructions such as “Pick up your shoes and put them in the closet.”?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Does your child climb onto and down from furniture without help?",
      "Can your child walk up and down stairs holding on?",
      "Does your child throw a ball overhead?",
      "Does your child make or copy straight lines and circles?",
      "Can your child name at least six body parts on a doll?",
      "Is half of your child’s speech understandable?",
      "Can your child make short sentences?",
    ],
  },
  {
    age: 26,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child name at least six body parts on a doll?",
      "Is half of your child’s speech understandable?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
    ],
  },
  {
    age: 27,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child name at least six body parts on a doll?",
      "Is half of your child’s speech understandable?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
    ],
  },
  {
    age: 28,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child name at least six body parts on a doll?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
    ],
  },
  {
    age: 29,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child name at least six body parts on a doll?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
    ],
  },
  {
    age: 30,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child name at least six body parts on a doll?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
      "Can your child brush teeth with help?",
      "Does your child wash and dry hands?",
    ],
  },
  {
    age: 31,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child name at least six body parts on a doll?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
      "Can your child brush teeth with help?",
      "Does your child wash and dry hands?",
    ],
  },
  {
    age: 32,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
      "Can your child build a tower of 7 or more building blocks?",
      "Can your child name at least 7 body parts?",
      "Can your child throw ball overarm?",
      "Does your child know his/her/their full name?",
    ],
  },
  {
    age: 33,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
      "Can your child build a tower of 7 or more building blocks?",
      "Can your child name at least 7 body parts?",
      "Can your child throw ball overarm?",
      "Does your child know his/her/their full name?",
    ],
  },
  {
    age: 34,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show some independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
      "Can your child build a tower of 7 or more building blocks?",
      "Can your child name at least 7 body parts?",
      "Can your child throw ball overarm?",
      "Does your child know his/her/their full name?",
      "Can your child eat with a fork",
      "Does your child carry on a conversation of two to three sentences?",
      "Can your child name at least four pictures in a book?",
    ],
  },
  {
    age: 35,
    question: [
      "Can your child take off own clothes without any help?",
      "Can your child make short sentences?",
      "Does your child follow simple instructions?",
      "Does your child repeat words he hears?",
      "Does your child points to things in a book?",
      "Does your child find things even when hidden under two or three covers?",
      "Is your child beginning to sort shapes and colours?",
      "Does your child complete sentneces and rhymes in familiar books?",
      "Does your child copy others, especially adults and older children?",
      "Does your child get excited when with other children?",
      "Does your child show independence?",
      "Does your child retain the skills it had before?",
      "Does your child name items in a picture book such as a cat, bird, or dog?",
      "Can your child stand on tiptoe?",
      "Can your child kick a ball?",
      "Has your child begun to run?",
      "Can your child throw a ball overarm?",
      "Can your child build a tower out of six building blocks?",
      "Can your child speak clearly most of the time?",
      "Can your child put on clothes?",
      "Does your child jump?",
      "Can your child build a tower of 7 or more building blocks?",
      "Can your child name at least 7 body parts?",
      "Can your child throw ball overarm?",
      "Does your child know his/her/their full name?",
      "Can your child eat with a fork?",
      "Does your child carry on a conversation of two to three sentences?",
      "Can your child name at least four pictures in a book?",
    ],
  },
  {
    age: 36,
    question: [
      "Is your child comfortable with stairs?",
      "Does your child have fairly clear speech?",
      "Does your child know how to work with simple toys like peg boards, simple puzzles, turning handle?",
      "Can your child describe how two objects are used?",
      "Does your child use four to five words in a sentence?",
      "Can your child name two actions (e.g. skipping, jumping)?",
      "Can your child catch a large ball in its arms?",
      "Does your child understand simple instructions?",
      "Does your child play pretend or make-believe?",
      "Does your child want to play with other children or with toys?",
      "Does your child make eye contact?",
      "Does your child retain skills he had earlier?",
      "Does your child copy adults and friends?",
      "Does your child show affection for friends?",
      "Does your child take turns in games?",
      "Does your child show concern for crying friend?",
      "Does your child understand the idea of  “mine” and “his” or “hers”?",
      "Does your child show a wide range of emotions?",
      "Does your child seperate easily from mom and dad?",
      "Does your child get upset with major changes in routine?",
      "Does your child dress and undress self?",
      "Does your child follow instructions with 2 or 3 steps?",
      "Does your child name most familiar things?",
      "Does your child understand words like “in,” “on,” and “under”?",
      "Does your child say first name, age and sex?",
      "Does your child name a friend?",
      "Does your child say words like “I,” “me,” “we,” and “you” and some plurals (cars, dogs, cats)?",
      "Does your child talk well enough for strangers to understand most of the time?",
      "Does your child carry on a conversation using 2 to 3 sentences?",
      "Can your child work with toys, buttons, levers, and moving parts?",
      "Does your child do puzzles with 3 or 4 pieces?",
      "Does your child understand what “two” means?",
      "Does your child copy a circle with pencil or crayon?",
      "Does your child screw and unscrew jar lids or turns door handle?",
      "Does your child climb well?",
      "Does your child run easily?",
      "Does your child pedal a tricycle?",
      "Does your child walk up and down stairs, one foor on each step?",
    ],
  },
  {
    age: 37,
    question: [
      "Can your child describe how two objects are used?",
      "Does your child use four to five words in a sentence?",
      "Can your child name two actions (e.g. skipping, jumping)?",
      "Can your child catch a large ball in its arms?",
    ],
  },
];

export default questions;
